# Use postgres/example user/password credentials
version: '3.1'

services:

  soketi:
    image: quay.io/soketi/soketi
    container_name: soketi
    restart: always
    env_file:
      - './.env'
    ports:
        - '${SOKETI_PORT:-6001}:6001'
        - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
   